lib/core_web/router.ex
defmodule CoreWeb.Router do
  use CoreWeb, :router

  use Pow.Phoenix.Router
  use PowAssent.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :core

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :guest do
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :superuser do
    plug :is_superuser
  end

  pipeline :check_totp do
    plug CoreWeb.TOTPPlug
  end

  pipeline :require_totp do
    plug CoreWeb.Require2FAForUserPlug
    plug CoreWeb.TOTPPlug
  end

  defp is_superuser(%{assigns: %{current_user: current_user}} = conn, _) do
    case current_user do
      nil  -> redir_and_halt(conn, to: CoreWeb.PowRoutes.user_not_authenticated_path(conn))
      _user -> case current_user.superuser do
        true  -> conn
        false -> redir_and_halt(conn, to: CoreWeb.PowRoutes.user_already_authenticated_path(conn))
      end
    end
  end
  defp is_superuser(conn, _), do: redir_and_halt(conn, to: CoreWeb.PowRoutes.user_not_authenticated_path(conn))

  defp redir_and_halt(conn, opts) do
    conn
    |> Phoenix.Controller.redirect(opts)
    |> Plug.Conn.halt()
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :need_auth_token do
    plug :check_auth_token
  end

  defp check_auth_token(conn, _) do
    conn
    |> get_req_header("x-auth-token")
    |> List.first()
    |> case do
      nil -> error_and_halt(conn, 401, "User not provided")
      token ->
        case Core.Accounts.get_user_by_auth_token(token) do
          nil -> error_and_halt(conn, 401, "User not found")
          user -> conn |> assign(:current_user, user)
        end
    end
  end

  defp error_and_halt(conn, code, message) do
    conn
    |> put_status(code)
    |> put_view(CoreWeb.APIView)
    |> render("error.json", message: message)
    |> Plug.Conn.halt()
  end

  scope "/", CoreWeb do
    pipe_through :browser

    resources "/register-totp", TOTPRegistrationController, only: [:new, :create, :delete]
    resources "/totp-phase", TOTPVerificationController, only: [:new, :create]
  end

  scope "/" do
    pipe_through [:browser, :check_totp]

    pow_routes()
    pow_extension_routes()
    pow_assent_routes()
  end

  scope "/", CoreWeb do
    pipe_through [:browser, :guest]

    # Add unprotected routes here
    get "/", PageController, :index
  end

  scope "/", CoreWeb do
    pipe_through [:browser, :protected, :check_totp]

    # Add protected routes here
    get "/dashboard", DashController, :index
    put "/dashboard/regen_token", DashController, :regenerate_token
    resources "/teams", TeamController, except: [:index] do
      resources "/roles", MembershipController, except: [:index, :show]
      resources "/accounts", AccountController, except: [:index] do
        get "/creds/new", AccountController, :new_creds
        post "/creds", AccountController, :create_creds
        get "/creds/edit", AccountController, :edit_creds
        put "/creds", AccountController, :update_creds
      end
      resources "/apps", AppController, except: [:index] do
        resources "/instances", InstanceController, except: [:index] do
          resources "/access", AccessController, except: [:index, :show]
        end
      end
    end
    resources "/adapters", AdapterController, only: [:create] do
      get "/share", AdapterController, :share_form
      post "/share", AdapterController, :share
      get "/unshare", AdapterController, :unshare_form
      post "/unshare", AdapterController, :unshare
    end
    resources "/accounts", AccountController, except: [:index] do
      get "/creds/new", AccountController, :new_creds
      post "/creds", AccountController, :create_creds
      get "/creds/edit", AccountController, :edit_creds
      put "/creds", AccountController, :update_creds
    end
    resources "/apps", AppController, except: [:index] do
      resources "/instances", InstanceController, except: [:index]
    end
  end

  scope "/super", CoreWeb do
    pipe_through [:browser, :superuser, :require_totp]

    # Add superuser routes here
    get "/", SuperController, :index
    post "/adapter/:adapter_id", SuperController, :make_global
    delete "/adapter/:adapter_id", SuperController, :make_local
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", CoreWeb.API, as: :api do
    pipe_through :api

    get "/", MiscController, :version
    get "/user_auth_token", UserController, :token
    get "/users/:slug/auth_token", UserController, :token
  end

  scope "/api/v1", CoreWeb.API, as: :api do
    pipe_through [:api, :need_auth_token]

    get "/users/:me", UserController, :show
    post "/adapters/:id", AdapterController, :register
    delete "/adapters/:id", AdapterController, :unregister
    resources "/apps", AppController, only: [:index, :show] do
      resources "/services", ServiceController, only: [:index, :show] do
        #
      end
    end
  end
end

lib/core/accounts/team.ex
defmodule Core.Accounts.Team do
  use Core.Schema
  import Ecto.Changeset

  schema "teams" do
    field :name, :string
    field :slug, :string

    has_many :memberships, Core.Accounts.TeamMembership
    has_many :users, through: [:memberships, :user]
    many_to_many :hosting_adapters, Core.Hosting.Adapter,
      join_through: Core.Hosting.TeamAdapter,
      join_keys: [team_id: :id, hosting_adapter_id: :id]
    has_many :hosting_accounts, Core.Hosting.Account
    has_many :apps, Core.Applications.App

    timestamps()
  end

  @doc false
  def changeset(team, attrs) do
    team = team
    |> cast(attrs, [:name])
    |> validate_required([:name])

    if Map.has_key?(team.changes, :name) do
      team.changes.name
    else
      team.data.name
    end
    |> case do
      nil ->
        team
      name ->
        team
        |> put_change(:slug, Slug.slugify(name))
    end
    |> unique_constraint([:slug])
  end
end

lib/core_web/controllers/team_controller.ex
defmodule CoreWeb.TeamController do
  use CoreWeb, :controller

  alias Core.Accounts
  alias Core.Accounts.Team

  def new(conn, _params) do
    changeset = Accounts.change_team(%Team{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"team" => team_params}) do
    case Accounts.create_team(team_params) do
      {:ok, team} ->
        conn = conn
        |> put_flash(:info, "Team created successfully.")

        case Accounts.create_team_membership(%{
          team_id: team.id,
          user_id: Pow.Plug.current_user(conn).id,
          role_id: Accounts.get_role_by_name!("Owner").id
        }) do
          {:ok, _membership} ->
            conn
            |> redirect(to: Routes.team_path(conn, :show, team))

          {:error, %Ecto.Changeset{} = changeset} ->
            render(conn, "new.html", changeset: changeset)
        end

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    team = Accounts.get_team!(id) |> Core.Repo.preload([:apps, :memberships, :hosting_adapters])
    case Core.Accounts.can_access_team(Pow.Plug.current_user(conn), team, "scope", "any") do
      true ->
        render(conn, "show.html", team: team, global_adapters: Core.Hosting.global_adapters())
      _else ->
        conn
        |> put_flash(:info, "That page is not available.")
        |> redirect(to: Routes.dash_path(conn, :index))
    end
  end

  def edit(conn, %{"id" => id}) do
    team = Accounts.get_team!(id)
    case Core.Accounts.can_access_team(Pow.Plug.current_user(conn), team, "scope", "admin") do
      true ->
        changeset = Accounts.change_team(team)
        render(conn, "edit.html", team: team, changeset: changeset)
      _else ->
        conn
        |> put_flash(:info, "That page is not available.")
        |> redirect(to: Routes.team_path(conn, :show, id))
    end
  end

  def update(conn, %{"id" => id, "team" => team_params}) do
    team = Accounts.get_team!(id)

    case Core.Accounts.can_access_team(Pow.Plug.current_user(conn), team, "scope", "admin") do
      true ->
        case Accounts.update_team(team, team_params) do
          {:ok, team} ->
            conn
            |> put_flash(:info, "Team updated successfully.")
            |> redirect(to: Routes.team_path(conn, :show, team))

          {:error, %Ecto.Changeset{} = changeset} ->
            render(conn, "edit.html", team: team, changeset: changeset)
        end
      _else ->
        conn
        |> put_flash(:info, "That page is not available.")
        |> redirect(to: Routes.team_path(conn, :show, id))
    end
  end

  def delete(conn, %{"id" => id}) do
    team = Accounts.get_team!(id) |> Core.Repo.preload([:memberships])
    case Core.Accounts.can_access_team(Pow.Plug.current_user(conn), team, "scope", "admin") do
      true ->
        team.memberships |> Enum.each(fn (membership) -> Accounts.delete_team_membership(membership) end)
        {:ok, _team} = Accounts.delete_team(team)

        conn
        |> put_flash(:info, "Team deleted successfully.")
        |> redirect(to: Routes.dash_path(conn, :index))
      _else ->
        conn
        |> put_flash(:info, "That page is not available.")
        |> redirect(to: Routes.team_path(conn, :show, id))
    end
  end
end

lib/core_web/views/team_view.ex
defmodule CoreWeb.TeamView do
  use CoreWeb, :view
end

lib/core_web/templates/team/edit.html.eex
<h1>Edit Team</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.team_path(@conn, :update, @team)) %>

<span><%= link "Back", to: Routes.dash_path(@conn, :index) %></span>

lib/core_web/templates/team/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>
  
  <%= error_tag f, :slug %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/core_web/templates/team/new.html.eex
<h1>New Team</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.team_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.dash_path(@conn, :index) %></span>

lib/core_web/templates/team/show.html.eex
<h1>Show Team</h1>

<ul>
  <li>
    <strong>Name:</strong>
    <%= @team.name %>
  </li>

  <li>
    <strong>Apps:</strong>
    <ul>
      <%= for app <- @team.apps |> Core.Repo.preload([:instances]) do %>
        <%= if Core.Accounts.can_access_team(@current_user, @team, "scope", "read") or Enum.any?(app.instances, fn instance -> Core.Accounts.can_access_instance(@current_user, instance, "scope", "read") end) do %>
          <li>
            <%= link app.name, to: Routes.team_app_path(@conn, :show, @team, app) %>
          </li>
        <% end %>
      <% end %>
      <%= if Core.Accounts.can_access_team(@current_user, @team, "scope", "write") do %>
        <li>
          <%= link "Add An App", to: Routes.team_app_path(@conn, :new, @team) %>
        </li>
      <% end %>
    </ul>
  </li>

<%= if Core.Accounts.can_access_team(@current_user, @team, "scope", "read") do %>
  <li>
    <strong>Members:</strong>
    <ul>
      <%= for membership <- @team.memberships |> Core.Repo.preload([:user, :role]) do %>
        <li>
          <%= membership.user.username %>
          (
            <%= if Core.Accounts.can_access_team(@current_user, @team, "scope", "admin") do %>
              <%= link membership.role.name, to: Routes.team_membership_path(@conn, :edit, @team, membership) %>
            <% else %>
              <%= membership.role.name %>
            <% end %>
          )
        </li>
      <% end %>
      <%= if Core.Accounts.can_access_team(@current_user, @team, "scope", "admin") do %>
        <li>
          <%= link "Add A Member", to: Routes.team_membership_path(@conn, :new, @team) %>
        </li>
      <% end %>
    </ul>
  </li>

  <li>
    <strong>Hosting Accounts:</strong>
    <ul>
      <%= for account <- @team |> Core.Repo.preload([:hosting_accounts]) |> Map.get(:hosting_accounts) do %>
        <%= if Core.Accounts.can_access_team(@current_user, @team, "scope", "edit") do %>
          <li><%= link account.name, to: Routes.team_account_path(@conn, :show, @team.id, account.id) %></li>
        <% else %>
          <li><%= account.name %></li>
        <% end %>
      <% end %>
      <%= if Core.Accounts.can_access_team(@current_user, @team, "scope", "edit") do %>
        <li><%= link "Create A New Hosting Account", to: Routes.team_account_path(@conn, :new, @team.id) %></li>
      <% end %>
    </ul>
  </li>

  <li>
    <strong>Hosting Adapters:</strong>
    <ul>
      <%= for adapter <- @team.hosting_adapters |> Core.Repo.preload([:user]) do %>
        <li>
          <%= adapter.name %>
          (
            <%= if adapter.global do %>
              Global
            <% else %>
              Shared by <%= adapter.user.username %>
            <% end %>
          )
        </li>
      <% end %>
      <%= for adapter <- @global_adapters do %>
        <%= unless Enum.any?(@team.hosting_adapters, fn (x) -> x.id == adapter.id end) do %>
          <li><%= adapter.name %> ( Global )</li>
        <% end %>
      <% end %>
    </ul>
  </li>
<% end %>
</ul>

<%= if Core.Accounts.can_access_team(@current_user, @team, "scope", "admin") do %>
  <span><%= link "Edit", to: Routes.team_path(@conn, :edit, @team) %></span>
  <span><%= link "Delete", to: Routes.team_path(@conn, :delete, @team), method: :delete %></span>
<% end %>
<span><%= link "Back", to: Routes.dash_path(@conn, :index) %></span>